version: "3.9"
services:
  app:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      TG_WEBHOOK_SECRET: ${TG_WEBHOOK_SECRET}
      HOST: 0.0.0.0
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped